### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by ghajini** [FireMasterK/BypassAdditions#1]
Doesn't bypass

https://linkvertise.com/16281/888.9713784870188/dynamic?r=aHR0cDovL3RvdGFsZGVicmlkLm9yZy9saWVucy9saWVuc3MvP2Fkcz1hSFIwY0RvdkwzUnZkR0ZzWkdWaWNtbGtMbTl5Wnk5c2FXVnVjeTlzYVdWdWMzTXZQMkZrY3oxaFNGSXdZMFJ2ZGt3elVuWmtSMFp6V2tkV2FXTnRiR3RNYlRsNVduazVjMkZYVm5WamVUbHpZVmRXZFdNelRYWlFNbEp6VUZSck1VNXRVVEZaYlVVeVRYcEZOVTFxU21sUFFUMDk%3D

Violentmonkey userscript manager

**Comment by FireMasterK** [comment]
Indentified the issue, a fix will be updated tomorrow.

**Comment by FireMasterK** [comment]
Fixed, update to 0.2.

**Comment by ghajini** [comment]
Why doesn't work in violentmonkey
