### ISSUE TITLE
Bypass 

### ISSUE THREAD

**Issue by ghajini** [FireMasterK/BypassAdditions#2]
make/bypass these annoying intermediate pages,these are everywhere on movies sites...

Eg

go here

 `moviesflixpro.org/download-netflix-cursed-season-1-hindi-720p/`

& click on onedrive download then comes annoying page techhubit.com, click, click

Final destination is `gdrivepro.xyz/view/hZJqtYNz4C`

Any solution to go directly go to final site skipping these annoying sites

2.

Another site
Downloads from 

`bolly4u.mobi`

Go through annoying `10desires.com` and click, click

Final destination is way far due to these annoying intermediate sites

**Comment by FireMasterK** [comment]
You should create an issue on Universal-Bypass, this project is for bypasses which cannot be added to Universal-Bypass.
