### ISSUE TITLE
titl2

### ISSUE THREAD

**Issue by peterxiyong** [FireMasterK/BypassAdditions#5]
I want to nullify this script `pastebin.com/TWEhsnwB`

Found on `https://streamtape.net/e/yB6lZWepjLSddJ/The.Fixies.Top.Secret.2017.WEB.H264-RBB.mp4`

& many others, so generic solution is preferrable

Via userscript, I have violentmonkey script manager

don't want to use ublock origin as i want generalised solution which will run once it detects above script  `pastebin.com/TWEhsnwB`

**Comment by FireMasterK** [comment]
Use ublock origin as this project is clearly not an adblocker, this project is for rules which cannot be added into Universal-Bypass.
