### ISSUE TITLE
Not Skipping

### ISSUE THREAD

**Issue by ripnonfegames** [FireMasterK/BypassAdditions#7]
So I'm trying to skip these linkvertise pages entirely, but it's not working, it doesn't skip it at all? Any help?

**Comment by FaolanX** [comment]
Still working here

**Comment by Techconix** [comment]
it just stopped working for me gonna reinstall

**Comment by FireMasterK** [comment]
Could you give an example link that doesn't work?

**Comment by VictorWolverine** [comment]
> Could you give an example link that doesn't work?

https://linkvertise.com/191217/KristenH?o=sharing

**Comment by ownserver** [comment]
Here too, after 02/27 doesn't work anymore.

Example links: 

- https://linkvertise.com/161166/11mar?o=sharing
- https://linkvertise.com/183849/10mar?o=sharing

best regards.

**Comment by Mayapixi** [comment]
same here it doesnt bypass anymore

**Comment by FireMasterK** [comment]
I have updated the script, it should work now.

Report here if it doesn't.

**Comment by Mayapixi** [comment]
thanks it works now!

**Comment by FireMasterK** [comment]
Ok, closing this issue then, thanks for testing!
